[package]
name = "wip"
version = "0.1.0"
authors = ["Matthew Conger-Eldeen <mceldeen@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"